#!/bin/bash

if [[ $1 = '-v' ]]; then
  echo Usage: rebase_branch [branch=master]
  exit
fi

# MAIN_BRANCH will use the first parameter or default to 'master'
MAIN_BRANCH=${1-master}
BRANCH=`git symbolic-ref HEAD | sed 's#refs/heads/##'`

BRANCH_HAS_DIRTY_FILES=`git diff-index --name-only HEAD --`

if [[ $MAIN_BRANCH = $BRANCH ]]; then
  echo "You are already on the $BRANCH branch"
  exit
fi

echo "Rebasing branch $BRANCH using $MAIN_BRANCH"

if [[ $BRANCH_HAS_DIRTY_FILES ]]; then
  echo "Stashing uncommitted changes"
  git stash
fi

echo "Checkout $MAIN_BRANCH"
git checkout $MAIN_BRANCH

echo "Pulling..."
git pull

echo "Re-checking out $BRANCH"
git checkout $BRANCH

echo "All your rebase is belong to Wong"
git rebase $MAIN_BRANCH

if [[ $BRANCH_HAS_DIRTY_FILES ]]; then
  echo "Unstashing the changes"
  git stash pop
fi

