#!/usr/bin/ruby

if ARGV[0] and ['-h', '--help'].include?(ARGV[0])
  usage
end

git_daemon_dir = ENV['GITDAEMONDIR']
if git_daemon_dir.nil?
  puts "GITDAEMONDIR environment variable not set"
  usage
  exit 1
end

if ARGV[0] && ARGV[0] == '-k'
  `ps aux | grep 'git.daemon' | grep -v grep | awk '{ print $2 }' | xargs kill`
  puts 'git-daemons killed!'
  exit
end

repos = `ls #{git_daemon_dir}`.split
receive_pack = ARGV[0] && ARGV[0] == '-r' ? '' :  '--enable=receive-pack'
if system("git daemon --base-path=#{git_daemon_dir} --export-all --verbose #{receive_pack} &")
  puts "git daemon started with PID=#{$$}"
  puts "Available repos:"
  repos.each do |repo|
    puts "    git://#{`hostname`.chomp}/#{repo}"
  end
end

def usage
  puts "gitdaemon [-h|--help|-k|-r]"
  puts "  -k            Kill daemons (if running)"
  puts "  -r            Start readonly"
  puts "  -h, --help    Show this message"
  exit 0
end
