#!/usr/bin/ruby
require 'rubygems'
require 'aws/s3'

unless ENV['AMAZON_ACCESS_KEY_ID'] && ENV['AMAZON_SECRET_ACCESS_KEY']
  puts "Please set the AMAZON_ACCESS_KEY_ID and AMAZON_SECRET_ACCESS_KEY environment variables"
  exit 1
end

# Parse out the command line arguments
if ARGV.length < 2
  puts "Usage: put_into_s3 FILENAME BUCKET [S3_FILENAME]"
  exit 1
end

action = :store
if ARGV[0] == '-d'
  action = :delete
  ARGV.shift
end

filename    = ARGV[0]
bucket      = ARGV[1]

if not File.exists? filename
  puts "#{filename} does not exist!"
  exit 1
end

basename = File.basename filename

AWS::S3::Base.establish_connection!(
  :access_key_id     => ENV['AMAZON_ACCESS_KEY_ID'],
  :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
)

if action == :store
  AWS::S3::S3Object.store(basename, open(filename), bucket)
else
  AWS::S3::S3Object.delete(basename, bucket)
end
