#!/usr/bin/ruby

Dir.chdir("#{ENV['HOME']}/.snippets")
snippets = Dir.glob("*")

snippets.each_with_index do |snippet, index|
  puts "#{index} :: #{snippet}"
end

print "Please select a result: "
choice = STDIN.gets.strip
if !choice.nil? && choice != "" && !(choice =~ /^[0-9]+$/).nil? && choice.to_i < snippets.length
  snippet = snippets[choice.to_i].strip
  system("cat #{snippets}")
end
